apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Nginx Demo</title>
      <style>
        body {
          width: 35em;
          margin: 0 auto;
          font-family: Tahoma, Verdana, Arial, sans-serif;
          background-color: #f0f0f0;
          padding: 20px;
        }
        .message {
          font-size: 24px;
          color: #333;
          background-color: #fff;
          padding: 20px;
          border-radius: 5px;
          box-shadow: 0 2px 5px rgba(0,0,0,0.1);
          margin-top: 20px;
        }
      </style>
    </head>
    <body>
      <h1>Nginx Demo for ArgoCD</h1>
      <div class="message">
        {{ .Values.message }}
      </div>
      <p>Deployed automatically by ArgoCD</p>
      <p>Last deployed: {{ now | date "2006-01-02 15:04:05" }}</p>
    </body>
    </html>