# Default values for nginx-demo
replicaCount: 1

image:
  repository: nginx
  tag: "1.21.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# This is our configurable message that will be displayed
# Change this value to see automatic updates through ArgoCD
message: "Hello from ArgoCD!! Version 1.0"

# Debug settings
debug:
  enabled: false  # Temporarily disable debug to fix sync issues
  showDetails: false
  logLevel: info

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi