# Default values for nginx-demo
replicaCount: 1

image:
  repository: nginx
  tag: "1.21.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  nodePort: 30080

message: "Hello from ArgoCD!123"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi