apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-secret-demo
  namespace: monitoring
  labels:
    app: aws-secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-secret-demo
  template:
    metadata:
      labels:
        app: aws-secret-demo
    spec:
      serviceAccountName: logzio-secrets-sa  # Using the trusted service account
      containers:
        - name: aws-secret-demo
          image: busybox
          command: ["sh", "-c", "while true; do echo 'Secret value: '; cat /mnt/secrets-store/demo-key; sleep 30; done"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secret-demo