{{- if .Values.debug.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-debug
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    debug.argocd-demo/purpose: "Verify namespace and cluster connectivity"
    debug.argocd-demo/version: "{{ .Chart.Version }}"
    debug.argocd-demo/timestamp: "{{ now | date "2006-01-02 15:04:05" }}"
  labels:
    app: {{ .Release.Name }}-debug
    component: debug
spec:
  restartPolicy: Never
  containers:
  - name: debug
    image: busybox:1.34
    command:
    - sh
    - -c
    - |
      echo "=== ArgoCD Debug Pod ==="
      echo "Checking DNS..."
      nslookup kubernetes.default.svc
      echo "Checking API access..."
      wget -q -O - --timeout=2 https://kubernetes.default.svc/api --no-check-certificate || echo "API unreachable"
      echo "Environment:"
      echo "Namespace: $NAMESPACE"
      echo "Chart Version: {{ .Chart.Version }}"
      echo "AppVersion: {{ .Chart.AppVersion }}"
      echo "===== Debug Values ====="
      echo "Debug enabled: {{ .Values.debug.enabled }}"
      echo "Debug log level: {{ .Values.debug.logLevel }}"
      echo "====== End Debug ======="
      echo "Debug pod completed successfully"
      exit 0
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
{{- end }}
