apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    debug.argocd-demo/version: "{{ .Chart.Version }}"
    debug.argocd-demo/timestamp: "{{ now | date "2006-01-02 15:04:05" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
