apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for ArgoCD Demo Applications

  # Allow manifests to deploy from any Git repository
  sourceRepos:
  - '*'

  # Only deploy to the specified cluster and namespaces
  destinations:
  - namespace: nginx-demo
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc

  # Allow specific cluster-scoped resources
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  # Allow specific namespace-scoped resources
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  # Define project roles and permissions
  roles:
  - name: project-admin
    description: Project admin rights
    policies:
    - p, proj:demo-project:project-admin, applications, *, demo-project/*, allow
    - p, proj:demo-project:project-admin, applicationsets, *, demo-project/*, allow
