apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-secret-dev
  namespace: demo-secret-dev-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-secret-dev
  template:
    metadata:
      labels:
        app: demo-secret-dev
    spec:
      serviceAccountName: demo-secret-dev-secrets-sa
      containers:
        - name: demo
          image: busybox:1.35
          command: ["/bin/sh"]
          args: ["-c", "echo '=== GitOps AWS Secrets Demo ==='; echo 'Environment Variable:' $DEMO_SECRET; echo 'Mounted File:'; cat /mnt/secrets/demo-key 2>/dev/null || echo 'File not found'; echo '\n================================'; echo 'Test completed successfully!'; sleep 600"]
          env:
            - name: DEMO_SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-secret-dev-k8s
                  key: secret-value
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "demo-secret-dev-spc"
      restartPolicy: Always