name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List and Read file
              run: |
                echo "My First Github Action Job"
                ls -ltra
                cat _INSTALLATION.md

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover" >> dragon.txt

            # - name: list files
            #   run: ls

            # - name: Read file
            #   run: cat _INSTALLATION.md