name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List Repo files
          run: ls -ltra
            
        - name: Executing shall script
          run: |
            chmod +x .github/workflows/generate-ascii.yaml
            .github/workflows/generate-ascii.yaml


